---
application:
  name: "tgmusic"
  project: "TGMusic"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "TGMusic"
  version: "4.4"
routers:
- name: "main-tgmusic"
  routes:
  - application_name: "tgmusic"
    paths:
    - "/*"
